### ISSUE TITLE
General description of knowledge graph components for Renku

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-graph#1]
This project's goal is to provide a central repository of metadata for the Renku platform. The metadata is to be collected into a Knowledge Graph which can be queried.

## Use cases
- Answer queries like which projects are using my datasets and how?
- Who else is using the same data inputs as me? Or the same type of data

## Architecture of the solution
The metadata store will be a graph database, JanusGraph (JG). JG is not an RDF store, so this will put some constraints on acceptable metadata (which can be desirable, to avoid storing junk metadata).

Components:
- JanusGraph
- Graph Service: a read-only server which interfaces client graphql queries to tinkerpop queries to JG. The service will also be responsible of applying access restrictions.
- Event Processor: this service will process a continuous stream of metadata event and reflect them into JG
- Event Store: Kafka / Block Chain (secure KG project). The two should be swappable.
- Event Miners: services responsible for producing metadata events from activity within Renku
    * GitLab miner: the first miner, will listen to project events and push project metadata, dataset metadata and lineage metadata to the event store

## Milestones
- [x] [Prototype the Graph Service](https://github.com/SwissDataScienceCenter/incubator-renku-graph/issues/2)
- [x] Import and refactor the existing event processor. See: https://github.com/SwissDataScienceCenter/incubator-renga-graph/tree/gitlab-miner/events-processor
- [x] Implement the 'admin' flavor of the GitLab miner, see: https://github.com/SwissDataScienceCenter/incubator-renga-graph/tree/gitlab-miner/gitlab-miner
- [x] implement the 'OAuth' flavor of the GitLab

**Comment by rokroskar** [comment]
I think all the points here have been resolved
