### ISSUE TITLE
No downtime re-provisioning

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#505]
As a Renku maintainer, I'd like the re-provisioning process to be transparent for the users and not affect the data available for them.

**The problem**
Currently, the re-provisioning process is very slow and it can take weeks to rebuild the whole Knowledge Graph DB. During that period, only the already re-provisioned data is available for the users so:
* they cannot see lineage on their projects (or they can only see parts of it);
* the dataset search shows data from already re-provisioned events only and so the results can be incomplete or even misleading as the users do not know about the undergoing re-provisioning process;
* the process, as it is now, prevents from other Renku components using KG as the only source of truth.

**The solution**
It seems reasonable and possible that there's a separate group of services performing re-provisioning to some other instance of the Triples Store (TS) while the _master_ group of services work as normal using the old version of Renku CLI. As long as the re-provisioning is ongoing, all the new events would continue to be processed by the _master_ services as well as the re-provisioning services. Once the process is finished, a swap of the services groups would happen and the old instance of Triples Store (TS) would not be provisioned any more. In regards to the _group of services_ term, it would probably be comprised of a set of triples-generators and maybe knowledge-graph (hopefully, the last one won't be needed in the group).

**Assumptions/Prerequisites**
* there's a schema version -> CLI version compatibility matrix in the config for all the schema versions ordered by schema version to be read on the start-up;
  * a TG when starts-up has to verify if the most recent schema version in the compatibility matrix matches schema version read from the installed Renku CLI.

**Use cases/scenarios**
* The version of triples in one of the TS instances is the same as the current schema version on the TGs and there's no `reProvisioningStatus -> running` triple on that TS instance.
  * All the TGs when they start-up and find out no re-provisioning is needed subscribe for new events and wait for some work to be sent to them.
* There's NO TS instance with the current schema version but there's some TS with some other schema version from the compatibility matrix and no `reProvisioningStatus -> running` triple on it (a TS the most recent schema version should be used).
  * The first TG that finds out re-provisioning should be triggered:
    * sets the`reProvisioningStatus -> running` triple on the TS instance with the schema version different than the most recent (from the perspective of the compatibility matrix);
    * sets the `provisioner -> TG's ping URL` in the TS instance with the most recent schema version;
    * updates schema version on the TS with the non-recent schema version;
    * removes all the triples on that instance (up to here the process is very similar to what's now);
    * (optional) spins up new TG instances (in number up to configured max TGs instances number);
    * reinstalls its own Renku CLI to the one supporting the most recent schema version found in one of the TS instances;
    * subscribes for the new events;
  * Any TG which starts-up:
    * checks if there's a TS instance with the `reProvisioningStatus -> running` triple and the current schema version;
    * finds out TG's URL in the TS instance with some other schema version;
      * if there's no URL or the ping does not work:
        * sets the `provisioner -> TG's ping URL` in the TS instance;
        * reinstalls its own Renku CLI to the one supporting schema version on that TS instance;
        * subscribes for the new events;
      * if the ping works, the TG subscribes for the re-provisioning events and starts producing triples to the TS instance under re-provisioning;
  * Any TG doing re-provisioning and not receiving events for more than 1 minute (while it has free slots for events) should:
    * try to renew the subscription for the re-provisioning events
      * if the renewal worked fine and there are still no events for the next 1 minute, it should remove the `reProvisioningStatus -> running` triple from the TS instance with the current schema version (the TS it was sending the triples during re-provisioning);
      * it should remove the re-provisioning subscription in the event-log and subscribe for the new events;
      * if the renewal failed, it should keep retrying until success and then follow the 1-minute inactivity procedure;
* There's no TS instance with either the current or any other supported schema version and effectively a non-background re-provisioning needs to be done.
  * The first TG that finds out re-provisioning should be triggered:
    * sets the`reProvisioningStatus -> running` triple on any of the TS instances;
    * updates schema version on that instance;
    * removes all the triples on that instance;
    * triggers all the events to be re-scheduled;
    * subscribes for the new events;
    * removes the`reProvisioningStatus -> running` triple;
    * (optional) spins up new TG instances (in number up to configured max TGs instances number);
  * Any TG which starts-up:
    * checks if there's a TS instance with the `reProvisioningStatus -> running` triple and the current schema version;
    * after finding out there's no TS instance with the supported schema version, the TG subscribes for the new events and starts producing triples to that TS under re-provisioning;
* There's a TS instance with some older supported schema version and a TS with the `reProvisioningStatus -> running` but schema version different than the current schema version. It's a case when re-provisioning wasn't finished but a new release with the new schema version happened.
  * The process should work as in the scenario where there's NO TS instance with the current schema version but there's a TS with some other schema version and no `reProvisioningStatus -> running` triple on it.
* The TG provisioning with some older schema version should use curation processes compatible with that version.
  * TG would need to get a mechanism for switching curation processes to match the schema version it operates; potentially, each of the curation processes might be compatible with several schema versions but the compatibility grid might be different for a specific curation process;
  * TG when starts-up has to be able to determine what's the current and other supported schema versions and eventually raise an error when there are missing curation process strategies for any of them;
* The KG has to be aware of all the TS instances and pick-up one to work with.
  * KG instance should read on the start-up the compatibility matrix and raise an exception if there's a schema version KG has no strategy to work with;
  * a TS instance with the most recent schema version and no `reProvisioningStatus -> running` triple on it should be used;
  * if there's no TS instance with schema version from the compatibility matrix but only one with the current schema version and `reProvisioningStatus -> running` triple on it, that one should be used;
  * the TS instance finding should be happening in one of the ways:
    * on every request;
    * the information might be cached and checked periodically;
    * the re-provisioning TG could be notifying KG about the process being finished;
  * KG to raise an exception if found TS instance is on schema version KG cannot work with (no strategy);
* The event-log (EL) should be able to accept subscriptions for the re-provisioning events.
  * the subscription payload for the re-provisioning events should look like:
  ```json
  {
    "subscriberUrl": "http://host/path",
    "category": "re-provisioning",
    "schemaVersion": 15
  }
  ```
  * EL to remove any active re-provisioning subscription to schema version different than the new subscription;
  * re-provisioning subscription to:
    * start popping events with status `NEW`, `TRIPLES_STORE` or `RECOVERABLE_FAILURE` and `schemaVersion` different than the one from the re-provisioning subscription (or null `schemaVersion`) or `RECOVERABLE_FAILURE` with `schemaVersion` matching the one from re-provisioning subscription;
    * change the `schemaVersion` on popped events;
    * deliver them to the subscribers;
  * subscription for the new events should be changed so it does not pick-up events in `RECOVERABLE_FAILURE` and non-null `schemaVersion`;
  * EL after receiving event status update should update relevant event's status in the DB regardless the `schemaVersion` is set or not on that event;

**Possible order of work**
- [ ] TG to switch to schema version instead from CLI version (that has to be done irrespectively of the no downtime re-provisioning) #532;
- [ ] Jena charts modification so two instances of Jena gets deployed;
- [ ] Info about URLs of both Jena instances to be injected to KG and TG;
- [ ] KG to work with all schema versions defined in the compatibility matrix at the same time;
- [ ] TG to work with all schema versions defined in the compatibility matrix at the same time;
- [ ] EL to allow subscriptions for the re-provisioning events;
- [ ] KG to be able to select a proper TS instance dynamically;
- [ ] TG to be able to change the version of Renku CLI installed on its box;
- [ ] TG to implement the logic for the background re-provisioning.

**Comment by jachro** [comment]
**Ideas:**
* we have two datasets one with the old schema, one with the new, the process could look like follows:
  * find out the re-provisioning start date;
  * the provisioning of the old schema events will continue to work as before;
  * we'll start migrating data to the new schema dataset (most recent commit per project); the project selection should use the same logic as for normal provisioning;
  * all the events that come after a project gets re-provisioned should be processed to the new schema dataset with the logic as for normal provisioning;
  * KG API should use the data from the old schema dataset until the new one is fully re-provisioned;
  * when everything is re-provisioned, we'd point KG to the new schema dataset and clear the old one;
* ~The re-provisioning process using DB migrations could look like this:~ (this approach seems to be very difficult to implement and what's even more problematic is that it's almost impossible how difficult could be the DB migrations and if it would be even possible to create them)
  * copy all the data from the old schema dataset to the new schema dataset;
  * run DB migrations one by one
  * once all the migrations are run, we'd start provisioning events that came after the re-provisioning start date
  * once all ready switch datasets
  * NOTES: 
    * we'd a mechanism to run migrations from any version in the past to the latest version; in a case when migration between several versions is needed, then we'd run migrations few times migrating by one version each time;
    * the migration functionality would need to be flexible in the sense that sometimes the migration would be purely DB script; other times it will be a mixture of DB query plus scala transformation; sometimes it could be complete re-provisioning

**Comment by jachro** [comment]
The idea is a bit less relevant now and probably very difficult do to.
